steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/civic-gate-439511-j2/frontend:${_TAG}', 
      '.'
    ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/civic-gate-439511-j2/frontend:${_TAG}'
    ]

images:
  # Specify the image that will be pushed to Artifact Registry
  - 'us-central1-docker.pkg.dev/civic-gate-439511-j2/frontend:${_TAG}'

